name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: windows-latest  # Change to Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Unit Tests
        run: pytest test_appp.py
      
      - name: Set up Docker on Windows
        run: |
          choco install docker-cli
          dockerd --register-service
          Start-Service docker
      
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/churn-prediction:latest .
      
      - name: Docker Hub Login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/churn-prediction:latest
